openapi: 3.0.0
info:
  title: API de Productos
  version: 1.0.0
  description: Documentación de la API para gestionar productos
servers:
  - url: http://localhost:3000
paths:
  /api/products:
    get:
      summary: Obtener todos los productos
      tags: [Productos]
      responses:
        '200':
          description: Lista de productos
    post:
      summary: Crear un nuevo producto
      tags: [Productos]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Producto creado
  /api/products/{id}:
    get:
      summary: Obtener producto por ID
      tags: [Productos]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Producto encontrado
        '404':
          description: Producto no encontrado
    put:
      summary: Actualizar un producto
      tags: [Productos]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Producto actualizado
        '404':
          description: Producto no encontrado
    delete:
      summary: Eliminar un producto
      tags: [Productos]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Producto eliminado
        '404':
          description: Producto no encontrado
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        price:
          type: number
        description:
          type: string
        category:
          type: string
        image:
          type: string
        rating:
          type: object
          properties:
            rate:
              type: number
            count:
              type: integer
